---

- block:
  - block:
    ### <POD> kind
    - name: read pod completion count
      command: "redis-cli get num_completion"
      register: num_completion

    - operator_sdk.util.k8s_status:
          api_version: ripsaw.cloudbulldozer.io/v1alpha1
          kind: Benchmark
          name: "{{ meta.name }}"
          namespace: "{{ operator_namespace }}"
          status:
            state: Run Next Set
        
      when: "num_completion.stdout|int == ((resource_state.resources[0].status.node_idx|int +1) * (resource_state.resources[0].status.pod_idx|int +1))"

    when: resource_kind == "pod"

    ### no <VM> kind block - Run a "set" is not yet supported

  when: resource_kind == "pod"

#
# No <VM> kind block - It has not been adapted to scale mode yet.
#
