---
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: kube-burner-configmap-cfg
  namespace: benchmark-operator
spec:
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: false
  prometheus:
    es_url: ${ES_SERVER}
    prom_token: ${PROMETHEUS_TOKEN}
    prom_url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
  workload:
    name: kube-burner
    args:
      extra_env_vars:
        ES_SERVER: ${ES_SERVER}
      configmap: kube-burner-config
      cleanup: true
      pin_server: {"node-role.kubernetes.io/worker": ""}
      image: quay.io/cloud-bulldozer/kube-burner:latest
      log_level: info
      step: 30s
      node_selector:
        key: node-role.kubernetes.io/worker
        value:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
