---
# tasks for http termination type.

- name: Create service for http type server pods
  k8s:
    definition: "{{ lookup('template', 'http-service.yml.j2') | from_yaml }}"
  with_sequence: start=0 count={{ workload_args.number_of_routes | int }}
  vars:
    type: http

- name: Create route for http type server pods
  k8s:
    definition: "{{ lookup('template', 'http-route.yml.j2') | from_yaml }}"
  with_sequence: start=0 count={{ workload_args.number_of_routes | int }}

- name: Start http server types(s)
  k8s:
    definition: "{{ lookup('template', 'nginx-server.yml.j2') | from_yaml }}"
  vars:
    type: http
  with_sequence: start=0 count={{ workload_args.number_of_routes | int }}