---

apiVersion: batch/v1
kind: "job"
metadata:
  name: "{{ meta.name }}-workload-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: hammerdb_workload-{{ trunc_uuid }}
    spec:
      containers:
      - name: hammerdb
        command: ["/bin/sh", "-c"]
        args: ["/usr/local/bin/uid_entrypoint; cd /hammer; ./hammerdbcli auto /workload/workload.tcl"]
        image: "quay.io/cloud-bulldozer/hammerdb:latest"
        volumeMounts:
        - name: hammerdb-workload-volume
          mountPath: "/workload"
          readOnly: false
      volumes:
      - name: hammerdb-workload-volume
        configMap:
          name: "{{ meta.name }}-workload-{{ trunc_uuid }}"
          defaultMode: 0640
      restartPolicy: OnFailure
