---
kind: Job
apiVersion: batch/v1
metadata:
  name: 'fio-client-{{ trunc_uuid }}'
  namespace: '{{ operator_namespace }}'
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: fiod-client-{{ trunc_uuid }}
        benchmark-uuid: {{ uuid }}
    spec:
{% if workload_args.runtime_class is defined %}
      runtimeClassName: "{{ workload_args.runtime_class }}"
{% endif %}
      containers:
      - name: fio-client
        image: {{ workload_args.image | default('quay.io/cloud-bulldozer/fio:latest') }}
        imagePullPolicy: Always
        env:
          - name: uuid
            value: "{{ uuid }}"
          - name: test_user
            value: "{{ test_user | default('ripsaw') }}"
          - name: clustername
            value: "{{ clustername }}"
          - name: ceph_cache_drop_pod_ip
            value: "{{ workload_args.rook_ceph_drop_cache_pod_ip | default() }}"
          - name: kcache_drop_pod_ips
            value: "{{ kcache_drop_pod_ips | default() }}"
          - name: KCACHE_DROP_PORT_NUM
            value: "{{ kernel_cache_drop_svc_port }}"
{% if ceph_osd_cache_drop_pod_ip is defined %}
          - name: ceph_osd_cache_drop_pod_ip
            value: "{{ ceph_osd_cache_drop_pod_ip }}"
          - name: CEPH_CACHE_DROP_PORT_NUM
            value: "{{ ceph_cache_drop_svc_port }}"
{% endif %}
{% if elasticsearch is defined %}
          - name: es
            value: "{{ elasticsearch.url }}"
          - name: es_index
            value: "{{ elasticsearch.index_name | default('ripsaw-fio') }}"
          - name: es_verify_cert
            value: "{{ elasticsearch.verify_cert | default(true) }}"
          - name: parallel
            value: "{{ elasticsearch.parallel | default(false) }}"
{% endif %}
{% if prometheus is defined %}
          - name: prom_es
            value: "{{ prometheus.es_url }}"
          - name: prom_parallel
            value: "{{ prometheus.es_parallel | default(false) }}"
          - name: prom_token
            value: "{{ prometheus.prom_token | default() }}"
          - name: prom_url
            value: "{{ prometheus.prom_url | default() }}"
{% endif %}
        command: ["/bin/sh", "-c"]
        args:
          - "cat /tmp/host/hosts;
{% if workload_args.prefill is defined and workload_args.prefill is sameas true %}
             echo ***************Prefill*****************;
             cat /tmp/fio/fiojob-prefill;
             mkdir -p /tmp/fiod-{{ uuid }}/fiojob-prefill;
             fio --client=/tmp/host/hosts /tmp/fio/fiojob-prefill --output-format=json;
{% if workload_args.post_prefill_sleep is defined %}
             sleep {{ workload_args.post_prefill_sleep }};
{% endif %}
             echo ***********End of Prefill*************;
{% endif %}
{% if workload_args.bsrange is defined %}
{% set loopvar = workload_args.bsrange %}
{% elif workload_args.bs is defined %}
{% set loopvar = workload_args.bs %}
{% endif %}
{% for numjobs in workload_args.numjobs %}
{% for i in loopvar %}
{% for job in workload_args.jobs %}
             cat /tmp/fio/fiojob-{{job}}-{{i}}-{{numjobs}}; mkdir -p /tmp/fiod-{{uuid}}/fiojob-{{job}}-{{i}}-{{numjobs}};
             run_snafu -t fio -H /tmp/host/hosts -j /tmp/fio/fiojob-{{job}}-{{i}}-{{numjobs}} -s {{workload_args.samples}} -d /tmp/fiod-{{ uuid }}/fiojob-{{job}}-{{i}}-{{numjobs}} \
{% if workload_args.debug is defined and workload_args.debug %}
             -v \
{% endif %}
             ;
{% if workload_args.fio_json_to_log is defined and workload_args.fio_json_to_log is sameas true %}
             for fio_sample in $(seq 1 {{workload_args.samples}});
             do echo START_FIO_JSON_OUTPUT_fiod-{{uuid}}_fiojob-{{job}}-{{i}}-{{numjobs}}_SAMPLE_$fio_sample;
             test -f /tmp/fiod-{{uuid}}/fiojob-{{job}}-{{i}}-{{numjobs}}/$fio_sample/{{job}}/fio-result.json && cat /tmp/fiod-{{uuid}}/fiojob-{{job}}-{{i}}-{{numjobs}}/$fio_sample/{{job}}/fio-result.json || echo ERROR_FIO_JSON_FILE_NOT_AVAILABLE;
             echo END_FIO_JSON_OUTPUT_fiod-{{uuid}}_fiojob-{{job}}-{{i}}-{{numjobs}}_SAMPLE_$fio_sample;done;
{% endif %}
{% endfor %}
{% endfor %}
{% endfor %}
             echo run finished"
        volumeMounts:
        - name: fio-volume
          mountPath: "/tmp/fio"
        - name: host-volume
          mountPath: "/tmp/host"
      volumes:
      - name: fio-volume
        configMap:
          name: "fio-test-{{ trunc_uuid }}"
          defaultMode: 0777
      - name: host-volume
        configMap:
          name: "fio-hosts-{{ trunc_uuid }}"
          defaultMode: 0777
      restartPolicy: Never
{% include "metadata.yml.j2" %}
