---
es: "{{ elasticsearch|default([]) }}"
es_server: "{{ es.server|default('') }}"
es_port: "{{ es.port|default(9200) }}"
es_index: "ripsaw-fio"
test_user: "ripsaw"
pin_server: "{{ fiod.pin_server|default('') }}"
rook_ceph_namespace: "{{ fiod.rook_ceph_namespace|default('rook-ceph') }}"
