apiVersion: bench.example.com/v1alpha1
kind: Bench
metadata:
  name: example-bench
spec:
  fio:
    # To disable fio, set num_clients to 0
    num_clients: 0
    test_type: randwrite
    direct: 1
    sync: 1
    filesize: 1
    directory: /tmp/
  uperf: 
    # To disable uperf, set pairs to 0
    pair: 1
    proto: tcp
    test_type: stream
    nthr: 2
    size: 16384
    runtime: 10
