kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: benchmark-operator
  namespace: my-ripsaw
subjects:
- kind: ServiceAccount
  name: benchmark-operator
  namespace: my-ripsaw
roleRef:
  kind: Role
  name: benchmark-operator
  apiGroup: rbac.authorization.k8s.io
