---
- name: Get benchmark state
  k8s_facts:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
  register: benchmark_state

- operator_sdk.util.k8s_status:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
    status:
      state: "Starting Scale Pod"
      complete: false
  when: benchmark_state.resources[0].status.state is not defined

- name: Get benchmark state 
  k8s_facts:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
  register: benchmark_state

- block:
  
  - name: Create scale pod
    k8s:
      state: present
      definition: "{{ lookup('template', 'scale.yml') }}"

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: "Scaling Cluster"

  when: benchmark_state.resources[0].status.state == "Starting Scale Pod"

- block:

  - name: Waiting for scaling pod to complete
    k8s_facts:
      kind: pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = scale-{{ trunc_uuid }}
    register: scale_pod

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Complete
        complete: true
    when: scale_pod|json_query('resources[].status[]')|selectattr('phase','match','Succeeded')

  when: benchmark_state.resources[0].status.state == "Scaling Cluster"
