apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: fio-vm-benchmark-example
  namespace: benchmark-operator
spec:
  # where elastic search is running
  elasticsearch:
    url: http://my.elasticsearch.server:80
    verify_cert: false
    parallel: false
  # clustername: myk8scluster
  # test_user: ripsaw
  workload:
    name: "fio_distributed"
    args:
      # if true, do large sequential write to preallocate volume before using
      prefill: true
      # number of times each test
      samples: 3
      # number of fio pods generating workload
      servers: 3
      # put all fio pods on this server
      pin_server: ''
      # Run fio servers in VMs
      kind: vm
      # Specify kubevirt registry image for server vm
      # This is helpful in disconnected environments and we assume
      # this VM image has all requirements already present
      vm_image: quay.io/mulbc/fed-fio
      # CPU cores that will be available inside the VM
      # Default: 1
      # vm_cores: 2
      # Memory that will be available inside the VM
      # Default: 5G
      # vm_memory: 10G
      # VM bus type: virtio, sata, or scsi
      # Default: virtio
      # vm_bus: virtio
      # test types, see fio documentation
      jobs:
        - write
        - read
        - randwrite
        - randread
      # I/O request sizes (also called block size)
      bs:
        - 4KiB
        - 64KiB
      # how many fio processes per pod
      numjobs:
        - 1
      # with libaio ioengine, number of in-flight requests per process
      iodepth:
        - 4
      # how long to run write tests, this is TOO SHORT DURATION
      read_runtime: 15
      # how long to run read tests, this is TOO SHORT DURATION
      write_runtime: 15
      # don't start measuring until this many seconds pass, for reads
      read_ramp_time: 5
      # don't start measuring until this many seconds pass, for writes
      write_ramp_time: 5
      # size of file to access
      filesize: 2GiB
      # interval between i/o stat samples in milliseconds
      log_sample_rate: 3000
      storageclass: ocs-storagecluster-ceph-rbd
      # Can be one of ReadWriteOnce,ReadOnlyMany,ReadWriteMany Default: ReadWriteOnce
      pvcaccessmode: ReadWriteMany
      # Can be one of Filesystem,Block Default: Filesystem
      pvcvolumemode: Block
      storagesize: 5Gi
#######################################
#  EXPERT AREA - MODIFY WITH CAUTION  #
#######################################
#  global_overrides:
#  NOTE: Dropping caches as per this example can only be done if the
#        fio server is running in a privileged pod
#    - exec_prerun=bash -c 'sync && echo 3 > /proc/sys/vm/drop_caches'
  job_params:
    - jobname_match: write
      params:
        - fsync_on_close=1
        - create_on_open=1
        - runtime={{workload_args.write_runtime }}
        - ramp_time={{workload_args.write_ramp_time }}
    - jobname_match: read
      params:
        - time_based=1
        - runtime={{workload_args.read_runtime }}
        - ramp_time={{workload_args.read_ramp_time }}
    - jobname_match: rw
      params:
        - rwmixread=50
        - time_based=1
        - runtime={{workload_args.read_runtime }}
        - ramp_time={{workload_args.read_ramp_time }}
    - jobname_match: readwrite
      params:
        - rwmixread=50
        - time_based=1
        - runtime={{workload_args.read_runtime }}
        - ramp_time={{workload_args.read_ramp_time }}
    - jobname_match: randread
      params:
        - time_based=1
        - runtime={{workload_args.read_runtime }}
        - ramp_time={{workload_args.read_ramp_time }}
    - jobname_match: randwrite
      params:
        - time_based=1
        - runtime={{workload_args.write_runtime }}
        - ramp_time={{workload_args.write_ramp_time }}
    - jobname_match: randrw
      params:
        - time_based=1
        - runtime={{workload_args.write_runtime }}
        - ramp_time={{workload_args.write_ramp_time }}
#    - jobname_match: <search_string>
#      params:
#        - key=value
