---

apiVersion: kubevirt.io/v1alpha3
kind: "VirtualMachineInstance"
metadata:
  name: "sysbench-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
  labels:
    kubevirt-vm: vm-sysbench-{{ trunc_uuid }}
    benchmark-uuid: {{ uuid }}
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: workload
    machine:
      type: ""
    resources:
      requests:
        memory: "1024M"
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: "{{ workload_args.image }}"
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/sh
        echo 'workload'
    name: workload
