---
- name: Deploy operator group
  k8s:
    definition: "{{ lookup('template', 'operatorgroup.yaml.j2') }}"

- name: Deploy catalog source
  k8s:
    definition: "{{ lookup('template', 'catalogsource.yaml.j2') }}"

- name: Wait for catalogsource to be ready...
  k8s_facts:
    kind: pod
    api_version: v1
    namespace: "{{ operator_namespace }}"
    label_selectors:
      - olm.catalogSource = operatorhubio-catalog
  register: cs_pod
  until: "'Running' in (cs_pod | json_query('resources[].status.phase'))"
  retries: 10
  delay: 10

