---
- name: Check for all clients to be ready
  shell: "redis-cli --raw llen pgb_client_ready"
  register: client_ready

- operator_sdk.util.k8s_status:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
    status:
      state: "Run Workload"
      complete: false
  when: client_ready.stdout|int == dbnum|int
