# Default values for benchmark-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""

# -- (string) overrides naming of all resources
fullnameOverride: "benchmark-operator"
operator:

  # -- how many replicas for the operator deployment
  replicaCount: 1

  image:
    repository: quay.io/cloud-bulldozer/benchmark-operator
    pullPolicy: Always
    tag: latest

  redisImage:
    repository: bitnami/redis
    pullPolicy: Always
    tag: latest

  resources:
    limits:
      cpu: "0.1"

  nodeSelector: {}

  tolerations:
  # -- schedule on a workload node even if it's tainted
  - key: role
    value: workload
    effect: NoSchedule

  affinity:
  # -- nodeAffinity is set to make the operator run on workload nodes, but it's not required
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/workload
            operator: In
            values:
            - ""
