---
kind: Job
apiVersion: batch/v1
metadata:
  name: "byowl-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ workload_args.job_timeout|default(3600) }}
  template:
    metadata:
      labels:
       app: byowl-{{ trunc_uuid }}
       benchmark-uuid: {{ uuid }}
    spec:
{% if workload_args.runtime_class is defined %}
      runtimeClassName: "{{ workload_args.runtime_class }}"
{% endif %}
{% if workload_args.specoptions is defined %}
{% for label, value in  workload_args.specoptions.items() %}
      {{ label }}: {{ value | to_json }}
{% endfor %}
{% endif %}
      containers:
      - name: byowl
        command: ["/bin/sh", "-c"]
        args: ["{{ workload_args.commands }}"]
        image: "{{ workload_args.image }}"
        imagePullPolicy: Always
{% if workload_args.containeroptions is defined %}
{% for label, value in  workload_args.containeroptions.items() %}
        {{ label }}: {{ value | to_json }}
{% endfor %}
{% endif %}
      restartPolicy: Never
{% if workload_args.nodeselector is defined %}
      nodeSelector: 
{% for label, value in  workload_args.nodeselector.items() %}
        {{ label | replace ("_", "-" )}}:{{ value }}
{% endfor %}
{% endif  %}
{% if workload_args.tolerations is defined %}
      tolerations:
        {{ workload_args.tolerations }}
{% endif %}
{% include "metadata.yml.j2" %}
