---
apiVersion: batch/v1
kind: "job"
metadata:
  name: "byowl-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: byowl-{{ trunc_uuid }}
    spec:
      containers:
      - name: byowl
        command: ["/bin/sh", "-c"]
        args: ["{{ byowl.commands }}"]
        image: "{{ byowl.image }}"
        wait: true
      restartPolicy: OnFailure
