---
# tasks for passthrough termination type.

- name: Create service for passthrough type server pods
  k8s:
    definition: "{{ lookup('template', 'https-service.yml.j2') | from_yaml }}"
  with_sequence: start=0 count={{ workload_args.number_of_routes | default(1)  | int }}
  vars:
    type: passthrough
  when: 
    - workload_args.serviceip is defined and workload_args.serviceip
    - ( workload_args.service_type | default("ClusterIP") == "NodePort" )

- name: Create route for passthrough type server pods
  k8s:
    definition: "{{ lookup('template', 'passthrough-route.yml.j2') | from_yaml }}"
  with_sequence: start=0 count={{ workload_args.number_of_routes | default(1)  | int }}

- name: Start passthrough server types(s)
  k8s:
    definition: "{{ lookup('template', 'nginx-server.yml.j2') | from_yaml }}"
  vars:
    type: passthrough
  with_sequence: start=0 count={{ workload_args.number_of_routes | default(1)  | int }}